# Generated by Django 4.1.7 on 2023-05-28 13:12

from decimal import Decimal

import apps.base.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('payment_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=apps.base.fields.MoneyField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=11,
                validators=[
                    django.core.validators.MinValueValidator(0, message='Insufficient Funds'),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='balancechange',
            name='amount',
            field=apps.base.fields.MoneyField(
                decimal_places=2,
                default=Decimal('0.00'),
                editable=False,
                max_digits=11,
                validators=[
                    django.core.validators.MinValueValidator(0, message='Should be positive value'),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='owner',
            name='income',
            field=apps.base.fields.MoneyField(
                decimal_places=2,
                default=Decimal('0.00'),
                editable=False,
                max_digits=11,
                validators=[
                    django.core.validators.MinValueValidator(0, message='Insufficient Funds'),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='owner',
            name='revenue',
            field=apps.base.fields.MoneyField(
                decimal_places=2,
                default=Decimal('0.00'),
                editable=False,
                max_digits=11,
                validators=[
                    django.core.validators.MinValueValidator(0, message='Insufficient Funds'),
                ],
            ),
        ),
    ]
