# Generated by Django 4.1.7 on 2023-05-28 13:12

from decimal import Decimal

import apps.base.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('item_purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='price_with_commission',
            field=apps.base.fields.MoneyField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=11,
                validators=[
                    django.core.validators.MinValueValidator(0, message='Should be positive value'),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='itempurchase',
            name='item_price',
            field=apps.base.fields.MoneyField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=11,
                validators=[
                    django.core.validators.MinValueValidator(0, message='Should be positive value'),
                    django.core.validators.MaxValueValidator(
                        10000,
                        message='Should be not greater than 10000',
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='amount',
            field=apps.base.fields.MoneyField(
                decimal_places=2,
                default=Decimal('0.00'),
                editable=False,
                max_digits=11,
                validators=[
                    django.core.validators.MinValueValidator(
                        0,
                        message='Should be a positive value',
                    ),
                ],
            ),
        ),
    ]
